name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
